
server:
  port: 9999
spring:
  application:
    name: account-service
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${password}
    url: ${db_url}
    username: ${username}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    kubernetes:
      ribbon:
        mode: POD
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true