apiVersion: v1
kind: Service
metadata:
  name: rss-account-service
  namespace: rss-account
  labels:
    app: rss-account-service
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: rss-account
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
